use_gpu: true

# data path
data_path: "pretrain/data/train_hsi.pkl"

# model path
init_model_path: "models/imagenet-vgg-m.mat"
model_path: "models/mdnet_vot-otb.pth"
#model_path: "models/11_epoch_49_shared_model.pth"

# input size
img_size: 107
padding: 16

# batch size
batch_frames: 8
batch_pos: 32
batch_neg: 96

# training examples sampling
trans_pos: 0.1
scale_pos: 1.3
trans_neg: 2
scale_neg: 1.6
overlap_pos: [0.7, 1]
overlap_neg: [0, 0.5]

# training
lr: 0.00001
grad_clip: 10
lr_mult: {"fc6": 10, "encoder": 1, "decoder": 1} # "fc": 10, 
# ft_layers: ["conv", "fc"]
ft_layers: ["fc6", "encoder", "decoder"]
n_cycles: 500
